name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Swatinem/rust-cache@v1
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: "Format"
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: "Build"
        with:
          command: build
          args: --locked

      - uses: actions-rs/cargo@v1
        name: "Clippy"
        with:
          command: clippy
          args: --locked -- -D warnings

      - uses: actions-rs/cargo@v1
        name: "Test"
        with:
          command: test
          args: --locked
